
// Updated listData.js
export const bangalorePropertiesData = [
  {
    id: 1,
    category: "Agricultural Land",
    title: "Agricultural Land for Sale",
    images: [
      "/properties/agricultural_land.jpg",
      "/properties/agriPic1.jpeg",
      "/properties/agri3.jpeg",
      // "/video.mp4",
    ],
    extent: "0.20 gunta",
    planlandplantation: "Plain Land",
    riversidebackwater: "no",
    location: "Mysore to Devalapura road",
    distance: "20 km from Mysore",
    village: "Hadinaru",
    road: "20 Km Tar road",
    soil: "Red",
    facing: "West and North",
    plantation: {
      Coconut: false,
      Arecanut: false,
      Mango: false,
      Sapota: false,
      Pomegranate: false,
      Teak: false,
      "Silver Oak": false,
    },
    fencing: "Fully fenced",
    borewell: false,
    openWell: false,
    farmhouse: false,
    pumpHouse: false,
    cowShed: false,
    pricePerGunta: "5 lakhs per gunta",
    totalPrice: "1 crore for 20 guntas",
  },
  {
    id: 2,
    category: "Commercial Plot",
    title: "Commercial Site for Sale",
    images: [
      "/properties/commercial_site.jpg", // First image
      "/properties/comPic.jpeg", // Second image
      "/properties/comPic2.jpeg", // Second image
    ],
    location: "Vijaya Nagara 1st stage",
    layoutName: "Vijaya Nagara 1st stage",
    siteDimension: "50x80",
    siteFacing: "West",
    siteNumber: 423,
    roadWidth: "80 feet",
    mudaAllotted: true,
    mudaApproved: false,
    dtcpApproved: false,
    pricePerSqft: "13,000/- per sqft",
    totalPrice: "5.20 crores",
  },
  {
    id: 3,
    category: "Residential Plot",
    title: "Residential Site for Sale",
    images: [
      "/properties/residential_site.jpg", // First image
      "/properties/rec1.jpeg", // Second image
      "/properties/rec2.jpeg", // Second image
    ],
    location: "Vijaya Nagara 4th stage",
    layoutName: "Vijaya Nagara 4th stage",
    siteDimension: "40x60",
    siteFacing: "West",
    siteNumber: 1523,
    roadWidth: "40 feet",
    mudaAllotted: true,
    mudaApproved: false,
    dtcpApproved: false,
    pricePerSqft: "6,500/- per sqft",
    totalPrice: "1.56 crores",
  },
  {
    id: 4,
    category: "Residential House/Villa",
    title: "Residential House for Sale",
    images: [
      "/properties/residential_house.jpg", // First image
      "/properties/res1.jpeg",
      "/properties/res2.jpeg",
      "/properties/res3.jpeg",
      "/properties/res4.jpeg",
      "/properties/res5.jpeg",
      "/properties/res6.jpeg",
      "/properties/res7.jpeg",
      "/properties/res8.jpeg",
      "/properties/res9.jpeg",
      "/properties/res10.jpeg",
      "/properties/res11.jpeg",
      "/properties/res12.jpeg",
      "/properties/res13.jpeg",
      "/properties/res14.jpeg",
      "/properties/res15.jpeg",
      "/properties/res16.jpeg",
      "/properties/res17.jpeg",
      "/properties/res18.jpeg",
      "/properties/res19.jpeg",
      "/properties/res20.jpeg",
      "/properties/res21.jpeg",
      "/properties/res22.jpeg",
      "/properties/res23.jpeg",
      "/properties/res24.jpeg",
      "/properties/res25.jpeg",
      "/properties/res26.jpeg",
      "/properties/res27.jpeg",
      "/properties/res28.jpeg",
    ],
    bhk: "3BHK",
    groundFloor: false,
    duplexground: "Duplex",
    buildersFloor: false,
    area: "Lingabuddi palya, inside Ring road",
    siteDimension: "36×40 = 1440 sqft",
    siteFacing: "North/West corner",
    mainDoorFacing: "East",
    roadWidth: "40 feet",
    mudaAllotted: false,
    mudaApproved: true,
    dtcpApproved: false,
    bedrooms: 3,
    attachBathrooms: 3,
    commonBathroom: 1,
    poojaRoom: 1,
    totalBuiltUpArea: "27 Squares",
    balconies: 1,
    totalFloors: "G + 1",
    semiFurnished: true,
    fullyFurnished: false,
    carParking: "Portico",
    totalPrice: "Rs. 2.10 crores",
  },
];

export const mysorePropertiesData = [
  {
    id: 1,
    category: "Agricultural Land",
    title: "Agricultural Plain Land for Sale",
    images: [
      "/properties/agricultural_land.jpg",
      "/properties/agricultural_land.jpg",
      // "/video.mp4",
    ],
    extent: "0.20 gunta",
    location: "Mysore to Devalapura road",
    distance: "20 km from Mysore",
    village: "Hadinaru",
    road: "20 Km Tar road",
    soil: "Red",
    facing: "West and North",
    plantation: {
      coconut: false,
      arecanut: false,
      mango: true,
      sapota: true,
      pomegranate: true,
      teak: false,
      banana: true,
    },
    fencing: "Fully fenced",
    borewell: false,
    openWell: true,
    farmhouse: true,
    pumpHouse: true,
    cowShed: true,
    pricePerGunta: "5 lakhs per gunta",
    totalPrice: "1 crore for 20 guntas",
  },
  {
    id: 2,
    category: "Commercial Plot",
    title: "Commercial Site for Sale",
    images: [
      "/properties/commercial_site.jpg", // First image
      "/properties/commercial_site.jpg", // Second image
    ],
    location: "Vijaya Nagara 1st stage",
    layoutName: "Vijaya Nagara 1st stage",
    siteDimension: "50x80",
    siteFacing: "West",
    siteNumber: 423,
    roadWidth: "80 feet",
    mudaAllotted: true,
    mudaApproved: false,
    dtcpApproved: false,
    pricePerSqft: "13,000/- per sqft",
    totalPrice: "5.20 crores",
  },
  {
    id: 3,
    category: "Residential Plot",
    title: "Residential Site for Sale",
    images: [
      "/properties/residential_site.jpg", // First image
      "/properties/residential_site.jpg", // Second image
    ],
    location: "Vijaya Nagara 4th stage",
    layoutName: "Vijaya Nagara 4th stage",
    siteDimension: "40x60",
    siteFacing: "West",
    siteNumber: 1523,
    roadWidth: "40 feet",
    mudaAllotted: true,
    mudaApproved: false,
    dtcpApproved: false,
    pricePerSqft: "6,500/- per sqft",
    totalPrice: "1.56 crores",
  },
  {
    id: 4,
    category: "Residential House/Villa",
    title: "Residential House for Sale",
    images: [
      "/properties/residential_house.jpg", // First image
      "/properties/residential_house.jpg", // Second image
    ],
    bhk: "3BHK",
    groundFloor: false,
    duplex: true,
    buildersFloor: false,
    area: "Lingabuddi palya, inside Ring road",
    siteDimension: "36×40 = 1440 sqft",
    siteFacing: "North/West corner",
    mainDoorFacing: "East",
    roadWidth: "40 feet",
    mudaAllotted: false,
    mudaApproved: true,
    dtcpApproved: false,
    bedrooms: 3,
    attachBathrooms: 3,
    commonBathroom: 1,
    poojaRoom: 1,
    totalBuiltUpArea: "27 Squares",
    balconies: 1,
    totalFloors: "G + 1",
    semiFurnished: true,
    fullyFurnished: false,
    carParking: "Portico",
    totalPrice: "Rs. 2.10 crores",
  },
];
