
// Updated listData.js
export const bangalorePropertiesData = [
  {
    id: 1,
    category: "Agricultural Land",
    title: "Agricultural Plain Land for Sale",
    images: [
      "/properties/bagi.jpeg",
      "/properties/bagi1.jpeg",
      "/properties/bagi2.jpeg",
      "/properties/bagi3.jpeg",
      // "/video.mp4",
    ],
    extent: "7.14  Acres",
    planlandplantation: "Tick mark",
    location: "Near Malavalli",
    distance: "65 km from Mysuru",
    village: "13 km from Malavalli ",
    road: "Full Tar road",
    soil: "Red",
    facing: "",
    plantation: {
      coconut: false,
      arecanut: false,
      mango: false,
      sapota: false,
      pomegranate: false,
      teak: false,
      "Silver Oak": false,
    },
    fencing: "",
    borewell: false,
    openWell: false,
    farmhouse: false,
    pumpHouse: false,
    cowShed: false,
    pricePerGunta: "1.125 lakhs per gunta",
    totalPrice: "3.30 Cr",
  },
  // {
  //   id: 2,
  //   category: "Commercial Plot",
  //   title: "Commercial Site for Sale",
  //   images: [
  //     "/properties/comPic.jpeg", //image
  //     "/properties/comPic2.jpeg", // Second image
  //   ],
  //   location: "Vijaya Nagara 1st stage",
  //   layoutName: "Vijaya Nagara 1st stage",
  //   siteDimension: "50x80",
  //   siteFacing: "West",
  //   siteNumber: 423,
  //   roadWidth: "80 feet",
  //   mudaAllotted: true,
  //   mudaApproved: false,
  //   dtcpApproved: false,
  //   pricePerSqft: "13,000/- per sqft",
  //   totalPrice: "5.20 crores",
  // },
  {
    id: 3,
    category: "Residential Plot",
    title: "Residential Site for Sale",
    images: [
      "/noimg.png"
      // "/properties/rec1.jpeg", // Second image
      // "/properties/rec2.jpeg", // Second image
    ],
    location: "Kengeri Satellite Town",
    layoutName: "",
    siteDimension: "40x60",
    siteFacing: "South",
    roadWidth: "80 feet",
    mudaAllotted: true,
    mudaApproved: false,
    dtcpApproved: false,
    pricePerSqft: "12,500/- per sqft",
    totalPrice: "3 crores",
  },
  {
    id: 4,
    category: "Residential House/Villa",
    title: "Residential House for Sale",
    images: [
      "/properties/bhouse1.jpeg",
      "/properties/bhouse2.jpeg",
      "/properties/bhouse3.jpeg",
      "/properties/bhouse4.jpeg",
      "/properties/bhouse5.jpeg",
    ],
    bhk: "3BHK",
    groundFloor: false,
    duplex: false,
    buildersFloor: false,
    area: "H N Layout, swimming pool extension, Malleshwarm, Bengaluru North",
    siteDimension: "30 × 40 = 1200 sqft",
    siteFacing: "North/West corner",
    mainDoorFacing: "South",
    roadWidth: "30 feet",
    bulding: "S + 5 Floors",
    mudaAllotted: false,
    mudaApproved: false,
    dtcpApproved: false,
    bedrooms: "2 Bedrooms ,1-attach, 1 common",
    attachBathrooms: 3,
    commonBathroom: 1,
    poojaRoom: "",
    totalBuiltUpArea: "5880 sqft",
    balconies: "",
    rent: "   2 Bhk-1 floor rent- 25,000/ month.  4 floors= 1,00,000/- ,1 Bhk- Top floor rent -15,000/ month. Total rent- 1,15,000/-",
    totalFloors: "5",
    semiFurnished: true,
    fullyFurnished: false,
    borewell: "1",
    Lift: "1",
    carParking: "5 covered",
    ageofthebuilding: "2.5 yrs",
    totalPrice: "Rs 4.45 Cr",
  },
  {
    id: 5,
    category: "Apartments",
    title: "APARTMENT FOR SALE",
    images: [
      "/properties/bapp.jpeg",
      "/properties/bapp1.jpeg",
      "/properties/bapp3.jpeg",
    ],
    location: "HRBR Layout, Kalyan nagar (Banasvadi), Near dubai office, Bengaluru East",
    projectname: "",
    bhks: "3 BHK",
    bedrooms: "3",
    facing: "West",
    Bathrooms: "3 attached, 1 common",
    Balconies: 4, 
    Totalnumberofflats: "1",
    ageoftheapartment: "20",
    TotalfloorsintheApartment: "5",
    Flatonfloornumber: "1",
    Flatsonthatfloor: "4",
    SemiFurnished: "Yes", 
    Furnished: "", 
    Builtuparea: "1350 sqft",
    Carpetarea: "1053 sqft",
    Superarea: "",
    Lift: "1",
    carparkingopenorcovered: 1, 
    Monthlymaintainacecharges: "5000",
    ageofthebuilding: "9 yrs",
    Price: "1.40 Cr",
  },
];

export const mysorePropertiesData = [
  {
    id: 1,
    category: "Agricultural Land",
    title: "Agricultural Land for Sale",
    images: [
      "/properties/agricultural_land.jpg",
      "/properties/agriPic1.jpeg",
      "/properties/agri3.jpeg",
      // "/video.mp4",
    ],
    extent: "0.20 gunta",
    planlandplantation: "Plain Land",
    riversidebackwater: "No",
    location: "Mysore to Devalapura road",
    distance: "20 km from Mysore",
    village: "Hadinaru",
    road: "20 Km Tar road",
    soil: "Red",
    facing: "West and North",
    plantation: {
      Coconut: false,
      Arecanut: false,
      Mango: false,
      Sapota: false,
      Pomegranate: false,
      Teak: false,
      "Silver Oak": false,
    },
    fencing: "Fully fenced",
    borewell: false,
    openWell: false,
    farmhouse: false,
    pumpHouse: false,
    cowShed: false,
    pricePerGunta: "5 lakhs per gunta",
    totalPrice: "1 crore for 20 guntas",
  },
  {
    id: 2,
    category: "Commercial Plot",
    title: "Commercial Site for Sale",
    images: [
      "/properties/comPic.jpeg", //image
      "/properties/comPic2.jpeg", // Second image
    ],
    location: "Vijaya Nagara 1st stage",
    layoutName: "Vijaya Nagara 1st stage",
    siteDimension: "50x80",
    totalArea: "4000 sqft",
    siteFacing: "West",
    siteNumber: 423,
    roadWidth: "80 feet",
    mudaAllotted: true,
    mudaApproved: false,
    dtcpApproved: false,
    pricePerSqft: "13,000/- per sqft",
    totalPrice: "5.20 crores",
  },
  {
    id: 3,
    category: "Residential Plot",
    title: "Residential Site for Sale",
    images: [
      "/properties/rec1.jpeg", // Second image
      "/properties/rec2.jpeg", // Second image
    ],
    location: "Vijaya Nagara 4th stage",
    layoutName: "Vijaya Nagara 4th stage",
    siteDimension: "40x60",
    totalArea: "2400 sqft",
    siteFacing: "West",
    siteNumber: 1523,
    roadWidth: "40 feet",
    mudaAllotted: true,
    mudaApproved: false,
    dtcpApproved: false,
    pricePerSqft: "6,500/- per sqft",
    totalPrice: "1.56 crores",
  },
  {
    id: 4,
    category: "Residential House/Villa",
    title: "Residential House for Sale",
    images: [
      "/properties/residential_house.jpg", // First image
      "/properties/res2.jpeg",
      "/properties/res3.jpeg",
      "/properties/res4.jpeg",
      "/properties/res5.jpeg",
      "/properties/res6.jpeg",
      "/properties/res7.jpeg",
      "/properties/res8.jpeg",
      "/properties/res9.jpeg",
      "/properties/res10.jpeg",
      "/properties/res11.jpeg",
      "/properties/res12.jpeg",
      "/properties/res13.jpeg",
      "/properties/res14.jpeg",
      "/properties/res15.jpeg",
      "/properties/res16.jpeg",
      "/properties/res17.jpeg",
      "/properties/res18.jpeg",
      "/properties/res19.jpeg",
      "/properties/res20.jpeg",
      "/properties/res22.jpeg",
      "/properties/res23.jpeg",
      "/properties/res24.jpeg",
      "/properties/res25.jpeg",
      "/properties/res26.jpeg",
      "/properties/res27.jpeg",
      "/properties/res28.jpeg",
    ],
    bhk: "3BHK",
    groundduplex: "Yes",
    buildersFloor: "No",
    area: "Lingabuddi palya, inside Ring road",
    siteDimension: "36×40 = 1440 sqft",
    siteFacing: "North/West corner",
    mainDoorFacing: "East",
    roadWidth: "40 feet",
    mudaAllotted: false,
    mudaApproved: true,
    dtcpApproved: false,
    bedrooms: 3,
    attachBathrooms: 3,
    commonBathroom: 1,
    poojaRoom: 1,
    totalBuiltUpArea: "27 Squares",
    balconies: 1,
    totalFloors: "G + 1",
    semiFurnished: true,
    fullyFurnished: false,
    carParking: "Portico",
    totalPrice: "Rs. 2.10 crores",
  },
  {
    id: 5,
    category: "Apartments",
    title: "APARTMENT FOR SALE",
    images: [
      "/properties/app1.jpeg",
      "/properties/app2.jpeg",
      "/properties/app3.jpeg",
      "/properties/app4.jpeg",
      "/properties/app5.jpeg",
    ],
    location: "Yadavagiri",
    projectname: "Brigade Tranquil",
    bhks: "3 BHK",
    bedrooms: "3",
    facing: "West",
    Bathrooms: "3 attached, 1 common",
    Balconies: 4, 
    Totalnumberofflats: "1",
    ageoftheapartment: "5",
    TotalfloorsintheApartment: "3",
    Flatonfloornumber: "1st ",
    Flatsonthatfloor: "2",
    SemiFurnished: "Yes", 
    Furnished: "", 
    Builtuparea: "2450 sqft",
    Carpetarea: "3000 sqft",
    Superarea: "",
    Lift: "1",
    carparkingopenorcovered: 2, 
    Monthlymaintainacecharges: "10,000",
    ageofthebuilding: "17 yrs",
    Price: "1.75 Cr",
  },
];
